### ISSUE TITLE
Top Support for Systematic Multiples

### ISSUE THREAD

**Issue by ElliotChong** [hash-bang/conkie-stats#1]
When `top` encounters a very large number it falls back to using [Systematic Multiples](https://en.wikipedia.org/wiki/Units_of_information) notation which is currently unsupported by the parsing RegExps.

For example, one of my processes is reporting `VIRT` as `0.125t` and `RES` as `4.195g`.

The end result of the RegExp failing to match is that the very beefy process you'd surely like to know about is not returned with the other processes.

Going to submit a PR which will resolve this, thanks for `conkie-stats`!

**Comment by hash-bang** [comment]
Thanks for this. Much appreciated!
